/* tslint:disable */
/* eslint-disable */

// ######################################## THIS FILE WAS GENERATED BY MONGOOSE-TSGEN ######################################## //

// NOTE: ANY CHANGES MADE WILL BE OVERWRITTEN ON SUBSEQUENT EXECUTIONS OF MONGOOSE-TSGEN.

import mongoose from "mongoose";

/**
 * Lean version of HomeDocument (type alias of `Home`)
 * 
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Home } from "../models"
 * import { HomeObject } from "../interfaces/mongoose.gen.ts"
 * 
 * const homeObject: HomeObject = home.toObject();
 * ```
 */
export type HomeObject = Home
/**
 * Mongoose Query types
 * 
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Home = mongoose.model<HomeDocument, HomeModel, HomeQueries>("Home", HomeSchema);
 * ```
 */
export type HomeQueries = {
}

export type HomeMethods = {
}

export type HomeStatics = {
}

/**
 * Mongoose Model type
 * 
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Home = mongoose.model<HomeDocument, HomeModel, HomeQueries>("Home", HomeSchema);
 * ```
 */
export interface HomeModel extends mongoose.Model<HomeDocument, HomeQueries>, HomeStatics {}

/**
 * Mongoose Schema type
 * 
 * Assign this type to new Home schema instances:
 * ```
 * const HomeSchema: HomeSchema = new mongoose.Schema({ ... })
 * ```
 */
export type HomeSchema = mongoose.Schema<HomeDocument, HomeModel>

/**
 * Lean version of HomeDocument
 * 
 * This has all Mongoose getters & functions removed. This type will be returned from `HomeDocument.toObject()`. To avoid conflicts with model names, use the type alias `HomeObject`.
 * ```
 * const homeObject = home.toObject();
 * ```
 */
export interface Home {
homeId?: string;
homeName?: string;
}

/**
 * Mongoose Document type
 * 
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Home = mongoose.model<HomeDocument, HomeModel, HomeQueries>("Home", HomeSchema);
 * ```
 */
export interface HomeDocument extends mongoose.Document<never, HomeQueries>, HomeMethods {
homeId?: string;
homeName?: string;
status: string;
}

/**
 * Lean version of DeviceHomeDocument
 * 
 * This has all Mongoose getters & functions removed. This type will be returned from `DeviceDocument.toObject()`.
 * ```
 * const deviceObject = device.toObject();
 * ```
 */
export interface DeviceHome {
homeId?: string;
homeName?: string;
}

/**
 * Lean version of DeviceDocument (type alias of `Device`)
 * 
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Device } from "../models"
 * import { DeviceObject } from "../interfaces/mongoose.gen.ts"
 * 
 * const deviceObject: DeviceObject = device.toObject();
 * ```
 */
export type DeviceObject = Device
/**
 * Mongoose Query types
 * 
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Device = mongoose.model<DeviceDocument, DeviceModel, DeviceQueries>("Device", DeviceSchema);
 * ```
 */
export type DeviceQueries = {
}

export type DeviceMethods = {
test: (this: DeviceDocument, ...args: any[]) => any;
}

export type DeviceStatics = {
test: (this: DeviceModel, ...args: any[]) => any;
}

/**
 * Mongoose Model type
 * 
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Device = mongoose.model<DeviceDocument, DeviceModel, DeviceQueries>("Device", DeviceSchema);
 * ```
 */
export interface DeviceModel extends mongoose.Model<DeviceDocument, DeviceQueries>, DeviceStatics {}

/**
 * Mongoose Schema type
 * 
 * Assign this type to new Device schema instances:
 * ```
 * const DeviceSchema: DeviceSchema = new mongoose.Schema({ ... })
 * ```
 */
export type DeviceSchema = mongoose.Schema<DeviceDocument, DeviceModel>

/**
 * Lean version of DeviceDocument
 * 
 * This has all Mongoose getters & functions removed. This type will be returned from `DeviceDocument.toObject()`. To avoid conflicts with model names, use the type alias `DeviceObject`.
 * ```
 * const deviceObject = device.toObject();
 * ```
 */
export interface Device {
name?: string;
_id: mongoose.Types.ObjectId;
home?: DeviceHome;
}

/**
 * Mongoose Document type
 * 
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Device = mongoose.model<DeviceDocument, DeviceModel, DeviceQueries>("Device", DeviceSchema);
 * ```
 */
export interface DeviceHomeDocument extends mongoose.Document<mongoose.Types.ObjectId> {
homeId?: string;
homeName?: string;
status: any;
}

/**
 * Mongoose Document type
 * 
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Device = mongoose.model<DeviceDocument, DeviceModel, DeviceQueries>("Device", DeviceSchema);
 * ```
 */
export interface DeviceDocument extends mongoose.Document<mongoose.Types.ObjectId, DeviceQueries>, DeviceMethods {
name?: string;
_id: mongoose.Types.ObjectId;
home?: DeviceHomeDocument;
}

/**
 * Lean version of Device2HomeDocument
 * 
 * This has all Mongoose getters & functions removed. This type will be returned from `Device2Document.toObject()`.
 * ```
 * const device2Object = device2.toObject();
 * ```
 */
export interface Device2Home {
homeId?: string;
homeName?: string;
}

/**
 * Lean version of Device2Document (type alias of `Device2`)
 * 
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Device2 } from "../models"
 * import { Device2Object } from "../interfaces/mongoose.gen.ts"
 * 
 * const device2Object: Device2Object = device2.toObject();
 * ```
 */
export type Device2Object = Device2
/**
 * Mongoose Query types
 * 
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Device2 = mongoose.model<Device2Document, Device2Model, Device2Queries>("Device2", Device2Schema);
 * ```
 */
export type Device2Queries = {
}

export type Device2Methods = {
test: (this: Device2Document, ...args: any[]) => any;
}

export type Device2Statics = {
test: (this: Device2Model, ...args: any[]) => any;
}

/**
 * Mongoose Model type
 * 
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Device2 = mongoose.model<Device2Document, Device2Model, Device2Queries>("Device2", Device2Schema);
 * ```
 */
export interface Device2Model extends mongoose.Model<Device2Document, Device2Queries>, Device2Statics {}

/**
 * Mongoose Schema type
 * 
 * Assign this type to new Device2 schema instances:
 * ```
 * const Device2Schema: Device2Schema = new mongoose.Schema({ ... })
 * ```
 */
export type Device2Schema = mongoose.Schema<Device2Document, Device2Model>

/**
 * Lean version of Device2Document
 * 
 * This has all Mongoose getters & functions removed. This type will be returned from `Device2Document.toObject()`. To avoid conflicts with model names, use the type alias `Device2Object`.
 * ```
 * const device2Object = device2.toObject();
 * ```
 */
export interface Device2 {
name?: string;
_id: mongoose.Types.ObjectId;
home?: Device2Home;
}

/**
 * Mongoose Document type
 * 
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Device2 = mongoose.model<Device2Document, Device2Model, Device2Queries>("Device2", Device2Schema);
 * ```
 */
export interface Device2HomeDocument extends mongoose.Document<mongoose.Types.ObjectId> {
homeId?: string;
homeName?: string;
status: any;
}

/**
 * Mongoose Document type
 * 
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Device2 = mongoose.model<Device2Document, Device2Model, Device2Queries>("Device2", Device2Schema);
 * ```
 */
export interface Device2Document extends mongoose.Document<mongoose.Types.ObjectId, Device2Queries>, Device2Methods {
name?: string;
_id: mongoose.Types.ObjectId;
home?: Device2HomeDocument;
}

/**
 * Lean version of Device3HomeDocument
 * 
 * This has all Mongoose getters & functions removed. This type will be returned from `Device3Document.toObject()`.
 * ```
 * const device3Object = device3.toObject();
 * ```
 */
export interface Device3Home {
homeId?: string;
homeName?: string;
}

/**
 * Lean version of Device3Document (type alias of `Device3`)
 * 
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Device3 } from "../models"
 * import { Device3Object } from "../interfaces/mongoose.gen.ts"
 * 
 * const device3Object: Device3Object = device3.toObject();
 * ```
 */
export type Device3Object = Device3
/**
 * Mongoose Query types
 * 
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Device3 = mongoose.model<Device3Document, Device3Model, Device3Queries>("Device3", Device3Schema);
 * ```
 */
export type Device3Queries = {
}

export type Device3Methods = {
test: (this: Device3Document, ...args: any[]) => any;
}

export type Device3Statics = {
test: (this: Device3Model, ...args: any[]) => any;
}

/**
 * Mongoose Model type
 * 
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Device3 = mongoose.model<Device3Document, Device3Model, Device3Queries>("Device3", Device3Schema);
 * ```
 */
export interface Device3Model extends mongoose.Model<Device3Document, Device3Queries>, Device3Statics {}

/**
 * Mongoose Schema type
 * 
 * Assign this type to new Device3 schema instances:
 * ```
 * const Device3Schema: Device3Schema = new mongoose.Schema({ ... })
 * ```
 */
export type Device3Schema = mongoose.Schema<Device3Document, Device3Model>

/**
 * Lean version of Device3Document
 * 
 * This has all Mongoose getters & functions removed. This type will be returned from `Device3Document.toObject()`. To avoid conflicts with model names, use the type alias `Device3Object`.
 * ```
 * const device3Object = device3.toObject();
 * ```
 */
export interface Device3 {
name?: string;
_id: mongoose.Types.ObjectId;
home?: Device3Home;
}

/**
 * Mongoose Document type
 * 
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Device3 = mongoose.model<Device3Document, Device3Model, Device3Queries>("Device3", Device3Schema);
 * ```
 */
export interface Device3HomeDocument extends mongoose.Document<mongoose.Types.ObjectId> {
homeId?: string;
homeName?: string;
status: any;
}

/**
 * Mongoose Document type
 * 
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Device3 = mongoose.model<Device3Document, Device3Model, Device3Queries>("Device3", Device3Schema);
 * ```
 */
export interface Device3Document extends mongoose.Document<mongoose.Types.ObjectId, Device3Queries>, Device3Methods {
name?: string;
_id: mongoose.Types.ObjectId;
home?: Device3HomeDocument;
}

/**
 * Lean version of Device4HomeDocument
 * 
 * This has all Mongoose getters & functions removed. This type will be returned from `Device4Document.toObject()`.
 * ```
 * const device4Object = device4.toObject();
 * ```
 */
export interface Device4Home {
homeId?: string;
homeName?: string;
}

/**
 * Lean version of Device4Document (type alias of `Device4`)
 * 
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { Device4 } from "../models"
 * import { Device4Object } from "../interfaces/mongoose.gen.ts"
 * 
 * const device4Object: Device4Object = device4.toObject();
 * ```
 */
export type Device4Object = Device4
/**
 * Mongoose Query types
 * 
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Device4 = mongoose.model<Device4Document, Device4Model, Device4Queries>("Device4", Device4Schema);
 * ```
 */
export type Device4Queries = {
}

export type Device4Methods = {
test: (this: Device4Document, ...args: any[]) => any;
}

export type Device4Statics = {
test: (this: Device4Model, ...args: any[]) => any;
}

/**
 * Mongoose Model type
 * 
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Device4 = mongoose.model<Device4Document, Device4Model, Device4Queries>("Device4", Device4Schema);
 * ```
 */
export interface Device4Model extends mongoose.Model<Device4Document, Device4Queries>, Device4Statics {}

/**
 * Mongoose Schema type
 * 
 * Assign this type to new Device4 schema instances:
 * ```
 * const Device4Schema: Device4Schema = new mongoose.Schema({ ... })
 * ```
 */
export type Device4Schema = mongoose.Schema<Device4Document, Device4Model>

/**
 * Lean version of Device4Document
 * 
 * This has all Mongoose getters & functions removed. This type will be returned from `Device4Document.toObject()`. To avoid conflicts with model names, use the type alias `Device4Object`.
 * ```
 * const device4Object = device4.toObject();
 * ```
 */
export interface Device4 {
name?: string;
_id: mongoose.Types.ObjectId;
home?: Device4Home;
}

/**
 * Mongoose Document type
 * 
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Device4 = mongoose.model<Device4Document, Device4Model, Device4Queries>("Device4", Device4Schema);
 * ```
 */
export interface Device4HomeDocument extends mongoose.Document<mongoose.Types.ObjectId> {
homeId?: string;
homeName?: string;
status: any;
}

/**
 * Mongoose Document type
 * 
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const Device4 = mongoose.model<Device4Document, Device4Model, Device4Queries>("Device4", Device4Schema);
 * ```
 */
export interface Device4Document extends mongoose.Document<mongoose.Types.ObjectId, Device4Queries>, Device4Methods {
name?: string;
_id: mongoose.Types.ObjectId;
home?: Device4HomeDocument;
}

/**
 * Lean version of DeviceDefaultHomeDocument
 * 
 * This has all Mongoose getters & functions removed. This type will be returned from `DeviceDefaultDocument.toObject()`.
 * ```
 * const devicedefaultObject = devicedefault.toObject();
 * ```
 */
export interface DeviceDefaultHome {
homeId?: string;
homeName?: string;
}

/**
 * Lean version of DeviceDefaultDocument (type alias of `DeviceDefault`)
 * 
 * Use this type alias to avoid conflicts with model names:
 * ```
 * import { DeviceDefault } from "../models"
 * import { DeviceDefaultObject } from "../interfaces/mongoose.gen.ts"
 * 
 * const devicedefaultObject: DeviceDefaultObject = devicedefault.toObject();
 * ```
 */
export type DeviceDefaultObject = DeviceDefault
/**
 * Mongoose Query types
 * 
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const DeviceDefault = mongoose.model<DeviceDefaultDocument, DeviceDefaultModel, DeviceDefaultQueries>("DeviceDefault", DeviceDefaultSchema);
 * ```
 */
export type DeviceDefaultQueries = {
}

export type DeviceDefaultMethods = {
test: (this: DeviceDefaultDocument) => string;
}

export type DeviceDefaultStatics = {
test: (this: DeviceDefaultModel) => string;
}

/**
 * Mongoose Model type
 * 
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const DeviceDefault = mongoose.model<DeviceDefaultDocument, DeviceDefaultModel, DeviceDefaultQueries>("DeviceDefault", DeviceDefaultSchema);
 * ```
 */
export interface DeviceDefaultModel extends mongoose.Model<DeviceDefaultDocument, DeviceDefaultQueries>, DeviceDefaultStatics {}

/**
 * Mongoose Schema type
 * 
 * Assign this type to new DeviceDefault schema instances:
 * ```
 * const DeviceDefaultSchema: DeviceDefaultSchema = new mongoose.Schema({ ... })
 * ```
 */
export type DeviceDefaultSchema = mongoose.Schema<DeviceDefaultDocument, DeviceDefaultModel>

/**
 * Lean version of DeviceDefaultDocument
 * 
 * This has all Mongoose getters & functions removed. This type will be returned from `DeviceDefaultDocument.toObject()`. To avoid conflicts with model names, use the type alias `DeviceDefaultObject`.
 * ```
 * const devicedefaultObject = devicedefault.toObject();
 * ```
 */
export interface DeviceDefault {
name?: string;
_id: mongoose.Types.ObjectId;
home?: DeviceDefaultHome;
}

/**
 * Mongoose Document type
 * 
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const DeviceDefault = mongoose.model<DeviceDefaultDocument, DeviceDefaultModel, DeviceDefaultQueries>("DeviceDefault", DeviceDefaultSchema);
 * ```
 */
export interface DeviceDefaultHomeDocument extends mongoose.Document<mongoose.Types.ObjectId> {
homeId?: string;
homeName?: string;
status: any;
}

/**
 * Mongoose Document type
 * 
 * Pass this type to the Mongoose Model constructor:
 * ```
 * const DeviceDefault = mongoose.model<DeviceDefaultDocument, DeviceDefaultModel, DeviceDefaultQueries>("DeviceDefault", DeviceDefaultSchema);
 * ```
 */
export interface DeviceDefaultDocument extends mongoose.Document<mongoose.Types.ObjectId, DeviceDefaultQueries>, DeviceDefaultMethods {
name?: string;
_id: mongoose.Types.ObjectId;
home?: DeviceDefaultHomeDocument;
}

