/* tslint:disable */
/* eslint-disable */

// ######################################## THIS FILE WAS GENERATED BY MONGOOSE-TSGEN ######################################## //

// NOTE: ANY CHANGES MADE WILL BE OVERWRITTEN ON SUBSEQUENT EXECUTIONS OF MONGOOSE-TSGEN.

import mongoose from "mongoose";

export interface UserFriend {uid: User["_id"] | User;
nickname?: string;
_id: mongoose.Types.ObjectId;
}

export type UserObject = User

export type UserQueries = {
populateFriends: <Q extends mongoose.Query<any, UserDocument>>(this: Q) => Q;
}

declare module "mongoose" {interface Query<ResultType, DocType extends Document> extends UserQueries {}}

export type UserMethods = {
isMetadataString: (this: UserDocument) => boolean;
}

export type UserStatics = {
getFriends: (this: UserModel, friendUids: UserDocument["_id"][]) => Promise<UserObject[]>;
}

export interface UserModel extends mongoose.Model<UserDocument>, UserStatics {}

export type UserSchema = mongoose.Schema<UserDocument, UserModel>

export interface User {
email: string;
firstName: string;
lastName: string;
metadata?: any;
bestFriend?: mongoose.Types.ObjectId;
friends: UserFriend[];
city: {
coordinates?: number[];
};
socialMediaHandles?: Map<string, string>;
arrayOfMaps: (Map<string, number>)[];
_id: mongoose.Types.ObjectId;
}

export type UserFriendDocument = mongoose.Types.EmbeddedDocument & {
uid: UserDocument["_id"] | UserDocument;
} & UserFriend

export type UserDocument = mongoose.Document<mongoose.Types.ObjectId> & UserMethods & {
metadata?: any;
friends: mongoose.Types.DocumentArray<UserFriendDocument>;
city: {
};
socialMediaHandles?: mongoose.Types.Map<string>;
arrayOfMaps: mongoose.Types.Array<mongoose.Types.Map<number>>;
name: string;
} & User

